In [10]:
install.packages("ggplot2")

Warning message:
"dependencies 'MASS', 'lattice' are not available"also installing the dependencies 'colorspace', 'utf8', 'nlme', 'Matrix', 'farver', 'labeling', 'munsell', 'R6', 'RColorBrewer', 'viridisLite', 'fansi', 'magrittr', 'pillar', 'pkgconfig', 'cli', 'glue', 'gtable', 'isoband', 'lifecycle', 'mgcv', 'rlang', 'scales', 'tibble', 'vctrs', 'withr'




  There are binary versions available but the source versions are later:
              binary  source needs_compilation
colorspace     2.0-1   2.1-0              TRUE
utf8           1.2.1   1.2.4              TRUE
nlme         3.1-152 3.1-164              TRUE
Matrix         1.3-3   1.6-5              TRUE
farver         2.1.0   2.1.1              TRUE
labeling       0.4.2   0.4.3             FALSE
R6             2.5.0   2.5.1             FALSE
RColorBrewer   1.1-2   1.1-3             FALSE
viridisLite    0.4.0   0.4.2             FALSE
fansi          0.4.2   1.0.6              TRUE
magrittr       2.0.1   2.0.3              TRUE
pillar         1.6.0   1.9.0             FALSE
cli            2.5.0   3.6.2              TRUE
glue           1.4.2   1.7.0              TRUE
gtable         0.3.0   0.3.4             FALSE
isoband        0.2.4   0.2.7              TRUE
lifecycle      1.0.0   1.0.4             FALSE
mgcv          1.8-35   1.9-1              TRUE
rlang         0.4.11   1.1.3     

installing the source packages 'labeling', 'R6', 'RColorBrewer', 'viridisLite', 'pillar', 'gtable', 'lifecycle', 'withr', 'ggplot2'

Warning message in install.packages("ggplot2"):
"installation of package 'lifecycle' had non-zero exit status"Warning message in install.packages("ggplot2"):
"installation of package 'pillar' had non-zero exit status"Warning message in install.packages("ggplot2"):
"installation of package 'gtable' had non-zero exit status"Warning message in install.packages("ggplot2"):
"installation of package 'ggplot2' had non-zero exit status"

In [11]:
x <- 1
paste("Imprimir valor")

[1] "Imprimir valor"

In [12]:
1

[1] 1

In [13]:
1+1

[1] 2

In [14]:
a <- 1

In [15]:
b = 1

In [16]:
a == b

[1] TRUE

In [17]:
class(a)

[1] "numeric"

In [18]:
class(b)

[1] "numeric"

In [22]:
msg <- "hola"
msg

[1] "hola"

In [21]:
msg

[1] "hola"

In [23]:
12/6

[1] 2

In [24]:
414184152181/581

[1] 712881501

In [28]:
x <- c(0.5, 0.6)

In [29]:
x

[1] 0.5 0.6

In [26]:
x <- c(0.5, 0.6)

In [27]:
x

[1]  TRUE FALSE

In [ ]:
x <- c(0.5, 0.6)

In [30]:
x <- vector("numeric", lenght 18)

ERROR: Error in parse(text = x, srcfile = src): <text>:1:31: unexpected numeric constant
1: x <- vector("numeric", lenght 18
                                  ^


In [31]:
y <- c(1.7, "a")
y

[1] "1.7" "a"

In [35]:
x <- c(0.5, 0.6)
x <- c(TRUE, FALSE)
x <- c(T,F)
x <- c("a", "b", "c")
x <- 9:29
x <- c(1+01, 2+41)

In [36]:
x

[1]  2 43

In [43]:
x <- vector("numeric", (lenght = 10))
x

[1] 0 0 0 0 0 0 0 0 0 0

In [48]:
print ("hola pequeña")

[1] "hola pequeña"


In [49]:
y = c(TRUE, 2)
paste

function (..., sep = " ", collapse = NULL) 
.Internal(paste(list(...), sep, collapse))
<bytecode: 0x000000005f6b62c0>
<environment: namespace:base>

In [50]:
m <- matrix(nrow =2, ncol = 3)
m

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [51]:
s <- matrix(nrow = 2, ncol = 3)
s

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [55]:
dim(m)

[1] 2 3

In [56]:
m <- matrix(1:6, nrow =2, ncol = 3)
m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [57]:
x <- 1:3
y <- 10:12
cbind(x,y)

x y 
[1,] 1 10
[2,] 2 11
[3,] 3 12

In [58]:
rbind(x,y)

[,1] [,2] [,3]
x  1    2    3  
y 10   11   12

In [59]:
x <- list(1, "a", TRUE, 1+4i)
x

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 1+4i

In [61]:
x <- factor(c("yes", "yes", "no", "yes", "no", "maybe"))
x

[1] yes   yes   no    yes   no    maybe
Levels: maybe no yes

In [65]:
x <- c(1,2,NA,10,3)
is.na(x) 

[1] FALSE FALSE  TRUE FALSE FALSE

In [66]:
iris

Sepal.Length Sepal.Width Petal.Length Petal.Width Species  
1   5.1          3.5         1.4          0.2         setosa   
2   4.9          3.0         1.4          0.2         setosa   
3   4.7          3.2         1.3          0.2         setosa   
4   4.6          3.1         1.5          0.2         setosa   
5   5.0          3.6         1.4          0.2         setosa   
6   5.4          3.9         1.7          0.4         setosa   
7   4.6          3.4         1.4          0.3         setosa   
8   5.0          3.4         1.5          0.2         setosa   
9   4.4          2.9         1.4          0.2         setosa   
10  4.9          3.1         1.5          0.1         setosa   
11  5.4          3.7         1.5          0.2         setosa   
12  4.8          3.4         1.6          0.2         setosa   
13  4.8          3.0         1.4          0.1         setosa   
14  4.3          3.0         1.1          0.1         setosa   
15  5.8          4.0         1.2          0.2         setosa   
16  5.7          4.4         1.5          0.4         setosa   
17  5.4          3.9         1.3          0.4         setosa   
18  5.1          3.5         1.4          0.3         setosa   
19  5.7          3.8         1.7          0.3         setosa   
20  5.1          3.8         1.5          0.3         setosa   
21  5.4          3.4         1.7          0.2         setosa   
22  5.1          3.7         1.5          0.4         setosa   
23  4.6          3.6         1.0          0.2         setosa   
24  5.1          3.3         1.7          0.5         setosa   
25  4.8          3.4         1.9          0.2         setosa   
26  5.0          3.0         1.6          0.2         setosa   
27  5.0          3.4         1.6          0.4         setosa   
28  5.2          3.5         1.5          0.2         setosa   
29  5.2          3.4         1.4          0.2         setosa   
30  4.7          3.2         1.6          0.2         setosa   
... ...          ...         ...          ...         ...      
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [69]:
class(iris)

[1] "data.frame"

In [70]:
read.table()
read.csv()
data.frame()

ERROR: Error in read.table(): el argumento "file" está ausente, sin valor por omisión


In [84]:
install.packages("tidyverse")

Warning message:
"dependency 'MASS' is not available"also installing the dependencies 'htmltools', 'processx', 'xfun', 'bslib', 'tinytex', 'lifecycle', 'glue', 'tidyselect', 'vctrs', 'gtable', 'scales', 'gargle', 'timechange', 'systemfonts', 'vroom', 'progress', 'callr', 'knitr', 'rmarkdown', 'broom', 'conflicted', 'cli', 'dbplyr', 'dplyr', 'dtplyr', 'forcats', 'ggplot2', 'googledrive', 'googlesheets4', 'haven', 'hms', 'jsonlite', 'lubridate', 'magrittr', 'modelr', 'pillar', 'purrr', 'ragg', 'readr', 'readxl', 'reprex', 'rlang', 'rvest', 'stringr', 'tibble', 'tidyr', 'xml2'




  There are binary versions available but the source versions are later:
               binary source needs_compilation
htmltools     0.5.1.1  0.5.7              TRUE
processx        3.5.2  3.8.3              TRUE
xfun             0.22   0.41              TRUE
bslib           0.2.4  0.6.1             FALSE
tinytex          0.31   0.49             FALSE
lifecycle       1.0.0  1.0.4             FALSE
glue            1.4.2  1.7.0              TRUE
tidyselect      1.1.1  1.2.0             FALSE
vctrs           0.3.8  0.6.5              TRUE
gtable          0.3.0  0.3.4             FALSE
scales          1.1.1  1.3.0              TRUE
gargle          1.1.0  1.5.2             FALSE
timechange      0.0.2  0.2.0              TRUE
systemfonts     1.0.2  1.0.5              TRUE
vroom           1.4.0  1.6.5              TRUE
progress        1.2.2  1.2.3             FALSE
callr           3.7.0  3.7.3             FALSE
knitr            1.33   1.45             FALSE
rmarkdown         2.8   2.25     

installing the source packages 'bslib', 'tinytex', 'lifecycle', 'tidyselect', 'gtable', 'gargle', 'progress', 'callr', 'knitr', 'rmarkdown', 'broom', 'conflicted', 'dbplyr', 'dtplyr', 'forcats', 'ggplot2', 'googledrive', 'googlesheets4', 'hms', 'modelr', 'pillar', 'reprex', 'rvest', 'stringr', 'tidyverse'

Warning message in install.packages("tidyverse"):
"installation of package 'tinytex' had non-zero exit status"Warning message in install.packages("tidyverse"):
"installation of package 'lifecycle' had non-zero exit status"Warning message in install.packages("tidyverse"):
"installation of package 'callr' had non-zero exit status"Warning message in install.packages("tidyverse"):
"installation of package 'knitr' had non-zero exit status"Warning message in install.packages("tidyverse"):
"installation of package 'conflicted' had non-zero exit status"Warning message in install.packages("tidyverse"):
"installation of package 'bslib' had non-zero exit status"Warning message in install.packag

In [85]:
library(tidyverse)

ERROR: Error in library(tidyverse): there is no package called 'tidyverse'


In [79]:
 %>%  %>% 

ERROR: Error in parse(text = x, srcfile = src): <text>:1:2: inesperado SPECIAL
1:  %>%
     ^


# hola
## hola
### hola
#### hola
##### hola
###### hola

In [86]:
data(mpg)
mpg

Warning message in data(mpg):
"data set 'mpg' not found"

ERROR: Error in eval(expr, envir, enclos): objeto 'mpg' no encontrado
